"""Blocksworld planning environment: exact checker, fitness, operators, prompts.

Everything here is offline (no model calls). ``search_adapter`` plugs an
instance into the shared loop in ``search/``. See README.md in this package.
"""

from .blocksworld import (
    BLOCKSWORLD_DOMAIN_PDDL,
    Action,
    Goal,
    Instance,
    InvalidAction,
    MoveCountBound,
    ParsedPlan,
    PlanParseError,
    SearchResult,
    State,
    apply,
    bfs_optimal_plan,
    generate_instance,
    generate_instance_set,
    goal_complete,
    goal_satisfied_count,
    move_count_bound,
    optimal_plan_length,
    parse_action,
    parse_plan,
    render_goal_natural_language,
    render_problem_pddl,
    render_state_natural_language,
    state_from_towers,
)
from .evaluation import (
    PlanEvaluation,
    evaluate_plan,
    fitness,
    fitness_exact,
    fitness_goal_count,
    outcome_bucket,
    progress,
    success,
    to_common_record,
)
from .operators import (
    OPERATOR_PROMPTS,
    OPERATORS,
    PlanningOperator,
    build_operator_prompt,
    sample_operator,
)
from .prompts import (
    SELF_REPORT_BLOCK,
    SUCCESS_EVENT,
    assert_no_hidden_information,
    build_initial_plan_prompt,
    build_mutation_prompt,
    build_plan_from_strategy_prompt,
    build_strategy_prompt,
    corrective_hint_block,
    inherited_rationale_block,
    render_checker_feedback,
    render_problem,
)

__all__ = [
    "BLOCKSWORLD_DOMAIN_PDDL",
    "Action",
    "Goal",
    "Instance",
    "InvalidAction",
    "MoveCountBound",
    "OPERATOR_PROMPTS",
    "OPERATORS",
    "ParsedPlan",
    "PlanEvaluation",
    "PlanParseError",
    "PlanningOperator",
    "SELF_REPORT_BLOCK",
    "SUCCESS_EVENT",
    "SearchResult",
    "State",
    "apply",
    "assert_no_hidden_information",
    "bfs_optimal_plan",
    "build_initial_plan_prompt",
    "build_mutation_prompt",
    "build_operator_prompt",
    "build_plan_from_strategy_prompt",
    "build_strategy_prompt",
    "corrective_hint_block",
    "evaluate_plan",
    "fitness",
    "fitness_exact",
    "fitness_goal_count",
    "generate_instance",
    "generate_instance_set",
    "goal_complete",
    "goal_satisfied_count",
    "inherited_rationale_block",
    "move_count_bound",
    "optimal_plan_length",
    "outcome_bucket",
    "parse_action",
    "parse_plan",
    "progress",
    "render_checker_feedback",
    "render_goal_natural_language",
    "render_problem",
    "render_problem_pddl",
    "render_state_natural_language",
    "sample_operator",
    "state_from_towers",
    "success",
    "to_common_record",
]
